import{hide_error,parse_api_error,show_error,show_success}from './modules/errors.js';import{postJSON}from './modules/requests.js';$(()=>{$('.login-toggle').click(e=>{e.preventDefault();hide_error();$('#recovery-box').hide(200);$('#register-box').hide(200);$('#login-box').show(200);});$('#register-toggle').click(e=>{e.preventDefault();hide_error();$('#recovery-box').hide(200);$('#register-box').show(200);$('#login-box').hide(200);});$('#forgot-password').click(e=>{e.preventDefault();hide_error();$('#recovery-box').show(200);$('#register-box').hide(200);$('#login-box').hide(200);});let type='';$('#login-button').click(e=>{e.preventDefault();type='login';grecaptcha.execute();});$('#register-button').click(e=>{e.preventDefault();type='register';grecaptcha.execute();});$('#recover-button').click(e=>{e.preventDefault();type='recovery';grecaptcha.execute();});function do_login(token){let username=$('#login-username').val();let password=$('#login-password').val();let two_factor=$('#two-factor').val();let remember=$('#remember-me').is(':checked');postJSON('/user/login',{username:username,password:password,two_factor:two_factor,remember:remember,recaptcha:token},data=>{if(data.status==='success'){if(data.cookie)
document.cookie=data.cookie;const params=new URLSearchParams(window.location.search);if(params.has('redirect'))
window.location.href=params.get('redirect');else
window.location=data.redirect;}else{parse_api_error(data);grecaptcha.reset();}});}
function do_register(token){let password=$('#register-password').val();let confirm_password=$('#confirm-password').val();if(password!==confirm_password){show_error('Passwords do not match');return;}
let username=$('#register-username').val();let referral=$('#referral-code').val();let email=$('#register-email').val();postJSON('/user/register',{username:username,email:email,password:password,recaptcha:token,referral:referral},data=>{if(data.status==='success'){show_success('Confirm your account by clicking the link in your email',0);const params=new URLSearchParams(window.location.search);if(params.has('redirect')){const redirect=params.get('redirect');setTimeout(()=>window.location.href=redirect,2000);}}else{parse_api_error(data);grecaptcha.reset();}});}
function do_recovery(token){postJSON('/user/reset-password',{username:$('#recovery-username').val(),recaptcha:token},()=>{grecaptcha.reset();show_success('If an account with your email or username exists, a password reset link will be sent to your email',0);});}
window.recaptcha_callback=token=>{if(type==='login')
do_login(token);else if(type==='register')
do_register(token);else if(type==='recovery')
do_recovery(token);};});